name-template: 'Stryker4s v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '🐛 Bugfixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Documentation'
    label: 'docs'
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
template: |
  $CHANGES
